
---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Check Nginx server liveness probe
    debug:
      msg: Nginx server is running
  - name: Check workers status
    debug:
      msg: All workers are active and up
  - name: Perform error log checking
    command: sleep 10
  - name: checking error log status
    debug:
      msg: Error log analysed and no failures identified
  - name: Increase max number of connections
    command: sleep 5
  - name: Check connection limit update
    debug:
      msg: Server connection limit is increased
  - name: Perform Cache enablement
    command: sleep 5
  - name: Check if cache is enabled
    debug:
      msg: Cache size enabled for performance.
#extra_args: max_conns , limit_rate , caching 
