
---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: IBM cloud login
    debug:
      msg: Login successfull !
  - name: Provisioning default server 
    command: sleep 60
  - name: Start VM
    debug:
      msg: VM is provisioned and running successfully